import Foundation

/// Curated catalog of common Unicode emojis grouped by category. Used by the
/// reaction picker and (later) the composer's `:shortcode:` autocomplete.
/// Not exhaustive — Chat web shows the full Unicode set, but ~250 covers the
/// 99% case and keeps bundle size + render cost trivial.
enum EmojiCatalog {
    struct Entry: Hashable, Identifiable {
        let emoji: String
        let name: String         // ":shortcode:" form (no colons stored — added at lookup)
        let keywords: [String]
        var id: String { emoji }
    }

    struct Category: Hashable, Identifiable {
        let id: String
        let title: String
        let symbol: String       // SF Symbol for the tab
        let entries: [Entry]
    }

    static let categories: [Category] = [
        Category(id: "smileys", title: "Smileys", symbol: "face.smiling", entries: [
            .init(emoji: "😀", name: "grinning", keywords: ["smile", "happy"]),
            .init(emoji: "😃", name: "smiley", keywords: ["happy"]),
            .init(emoji: "😄", name: "smile", keywords: ["happy"]),
            .init(emoji: "😁", name: "grin", keywords: []),
            .init(emoji: "😂", name: "joy", keywords: ["laugh", "tears"]),
            .init(emoji: "🤣", name: "rofl", keywords: ["lol", "laugh"]),
            .init(emoji: "😅", name: "sweat_smile", keywords: ["nervous"]),
            .init(emoji: "😊", name: "blush", keywords: ["shy"]),
            .init(emoji: "🙂", name: "slight_smile", keywords: []),
            .init(emoji: "🙃", name: "upside_down", keywords: []),
            .init(emoji: "😉", name: "wink", keywords: []),
            .init(emoji: "😍", name: "heart_eyes", keywords: ["love"]),
            .init(emoji: "🥰", name: "smiling_face_with_hearts", keywords: ["love"]),
            .init(emoji: "😘", name: "kissing_heart", keywords: ["love"]),
            .init(emoji: "😜", name: "stuck_out_tongue_winking", keywords: ["tongue"]),
            .init(emoji: "🤪", name: "zany", keywords: ["crazy"]),
            .init(emoji: "🤔", name: "thinking", keywords: ["hmm"]),
            .init(emoji: "🫡", name: "salute", keywords: ["respect"]),
            .init(emoji: "🤗", name: "hug", keywords: ["hugging"]),
            .init(emoji: "😎", name: "sunglasses", keywords: ["cool"]),
            .init(emoji: "🥳", name: "partying", keywords: ["party"]),
            .init(emoji: "😏", name: "smirk", keywords: []),
            .init(emoji: "🙄", name: "roll_eyes", keywords: []),
            .init(emoji: "😬", name: "grimace", keywords: ["awkward"]),
            .init(emoji: "😴", name: "sleeping", keywords: ["sleep", "tired"]),
            .init(emoji: "🥱", name: "yawn", keywords: ["tired"]),
            .init(emoji: "😪", name: "sleepy", keywords: ["tired"]),
            .init(emoji: "🤤", name: "drool", keywords: []),
            .init(emoji: "😋", name: "yum", keywords: ["tasty"]),
            .init(emoji: "😛", name: "stuck_out_tongue", keywords: []),
            .init(emoji: "🤓", name: "nerd", keywords: ["geek"]),
            .init(emoji: "😱", name: "scream", keywords: ["shock"]),
            .init(emoji: "😨", name: "fearful", keywords: ["scared"]),
            .init(emoji: "😰", name: "cold_sweat", keywords: ["worry"]),
            .init(emoji: "😢", name: "cry", keywords: ["sad", "tears"]),
            .init(emoji: "😭", name: "sob", keywords: ["sad", "cry"]),
            .init(emoji: "😤", name: "huff", keywords: ["mad"]),
            .init(emoji: "😡", name: "rage", keywords: ["angry"]),
            .init(emoji: "🤯", name: "exploding_head", keywords: ["mind", "blown"]),
            .init(emoji: "🤐", name: "zipper_mouth", keywords: ["quiet"]),
            .init(emoji: "🥺", name: "pleading", keywords: ["puppy"]),
            .init(emoji: "🤷", name: "shrug", keywords: ["dunno"]),
            .init(emoji: "🤦", name: "facepalm", keywords: []),
            .init(emoji: "💀", name: "skull", keywords: ["dead"]),
            .init(emoji: "👻", name: "ghost", keywords: ["boo"]),
            .init(emoji: "🤖", name: "robot", keywords: ["bot"]),
            .init(emoji: "💩", name: "poop", keywords: []),
        ]),
        Category(id: "gestures", title: "Gestures", symbol: "hand.thumbsup", entries: [
            .init(emoji: "👍", name: "thumbsup", keywords: ["yes", "plus_one", "+1"]),
            .init(emoji: "👎", name: "thumbsdown", keywords: ["no", "-1"]),
            .init(emoji: "👌", name: "ok_hand", keywords: ["good"]),
            .init(emoji: "🤌", name: "pinched_fingers", keywords: ["italian"]),
            .init(emoji: "🤏", name: "pinching_hand", keywords: ["small"]),
            .init(emoji: "✌️", name: "peace", keywords: ["victory"]),
            .init(emoji: "🤞", name: "crossed_fingers", keywords: ["luck"]),
            .init(emoji: "🤟", name: "love_you", keywords: []),
            .init(emoji: "🤘", name: "rock", keywords: ["metal"]),
            .init(emoji: "🤙", name: "call_me", keywords: ["shaka"]),
            .init(emoji: "👈", name: "point_left", keywords: []),
            .init(emoji: "👉", name: "point_right", keywords: []),
            .init(emoji: "👆", name: "point_up", keywords: []),
            .init(emoji: "👇", name: "point_down", keywords: []),
            .init(emoji: "☝️", name: "point_index", keywords: []),
            .init(emoji: "✋", name: "raised_hand", keywords: ["stop"]),
            .init(emoji: "🤚", name: "back_of_hand", keywords: []),
            .init(emoji: "🖐", name: "five_fingers", keywords: []),
            .init(emoji: "🖖", name: "vulcan", keywords: ["spock"]),
            .init(emoji: "👋", name: "wave", keywords: ["hi", "bye"]),
            .init(emoji: "🤝", name: "handshake", keywords: ["deal"]),
            .init(emoji: "🙏", name: "pray", keywords: ["thanks", "please"]),
            .init(emoji: "✍️", name: "writing", keywords: []),
            .init(emoji: "💪", name: "muscle", keywords: ["strong"]),
            .init(emoji: "👏", name: "clap", keywords: ["applause"]),
            .init(emoji: "🙌", name: "raised_hands", keywords: ["hooray"]),
            .init(emoji: "🫶", name: "heart_hands", keywords: ["love"]),
            .init(emoji: "👀", name: "eyes", keywords: ["looking"]),
            .init(emoji: "🧠", name: "brain", keywords: ["smart"]),
            .init(emoji: "🦾", name: "mechanical_arm", keywords: []),
        ]),
        Category(id: "hearts", title: "Hearts", symbol: "heart", entries: [
            .init(emoji: "❤️", name: "heart", keywords: ["love"]),
            .init(emoji: "🧡", name: "orange_heart", keywords: []),
            .init(emoji: "💛", name: "yellow_heart", keywords: []),
            .init(emoji: "💚", name: "green_heart", keywords: []),
            .init(emoji: "💙", name: "blue_heart", keywords: []),
            .init(emoji: "💜", name: "purple_heart", keywords: []),
            .init(emoji: "🖤", name: "black_heart", keywords: []),
            .init(emoji: "🤍", name: "white_heart", keywords: []),
            .init(emoji: "🤎", name: "brown_heart", keywords: []),
            .init(emoji: "❣️", name: "heart_exclaim", keywords: []),
            .init(emoji: "💕", name: "two_hearts", keywords: []),
            .init(emoji: "💞", name: "revolving_hearts", keywords: []),
            .init(emoji: "💓", name: "heartbeat", keywords: []),
            .init(emoji: "💗", name: "growing_heart", keywords: []),
            .init(emoji: "💖", name: "sparkling_heart", keywords: []),
            .init(emoji: "💘", name: "cupid", keywords: []),
            .init(emoji: "💝", name: "gift_heart", keywords: []),
            .init(emoji: "💔", name: "broken_heart", keywords: []),
        ]),
        Category(id: "celebration", title: "Celebration", symbol: "party.popper", entries: [
            .init(emoji: "🎉", name: "tada", keywords: ["party", "celebrate"]),
            .init(emoji: "🎊", name: "confetti", keywords: ["party"]),
            .init(emoji: "🎂", name: "birthday", keywords: ["cake"]),
            .init(emoji: "🍰", name: "cake", keywords: []),
            .init(emoji: "🍾", name: "champagne", keywords: ["celebrate"]),
            .init(emoji: "🥂", name: "cheers", keywords: ["toast"]),
            .init(emoji: "🍻", name: "beers", keywords: ["cheers"]),
            .init(emoji: "🎁", name: "gift", keywords: ["present"]),
            .init(emoji: "🎈", name: "balloon", keywords: ["party"]),
            .init(emoji: "🏆", name: "trophy", keywords: ["winner"]),
            .init(emoji: "🥇", name: "first_place", keywords: ["gold"]),
            .init(emoji: "🌟", name: "star", keywords: []),
            .init(emoji: "⭐️", name: "star2", keywords: []),
            .init(emoji: "✨", name: "sparkles", keywords: []),
            .init(emoji: "🔥", name: "fire", keywords: ["lit", "hot"]),
            .init(emoji: "💯", name: "hundred", keywords: ["100"]),
            .init(emoji: "💥", name: "boom", keywords: []),
            .init(emoji: "⚡️", name: "zap", keywords: ["lightning"]),
            .init(emoji: "🚀", name: "rocket", keywords: ["ship", "launch"]),
            .init(emoji: "🎯", name: "target", keywords: ["bullseye"]),
        ]),
        Category(id: "objects", title: "Objects", symbol: "lightbulb", entries: [
            .init(emoji: "✅", name: "check", keywords: ["yes", "done"]),
            .init(emoji: "☑️", name: "ballot_check", keywords: []),
            .init(emoji: "❌", name: "x", keywords: ["no"]),
            .init(emoji: "⛔️", name: "no_entry", keywords: ["stop"]),
            .init(emoji: "🚫", name: "prohibited", keywords: ["no"]),
            .init(emoji: "⚠️", name: "warning", keywords: []),
            .init(emoji: "❓", name: "question", keywords: ["help"]),
            .init(emoji: "❗️", name: "exclamation", keywords: []),
            .init(emoji: "💡", name: "bulb", keywords: ["idea"]),
            .init(emoji: "📌", name: "pin", keywords: []),
            .init(emoji: "📍", name: "round_pin", keywords: []),
            .init(emoji: "🔖", name: "bookmark", keywords: []),
            .init(emoji: "🔗", name: "link", keywords: []),
            .init(emoji: "📎", name: "paperclip", keywords: ["attach"]),
            .init(emoji: "📞", name: "phone", keywords: []),
            .init(emoji: "📧", name: "email", keywords: []),
            .init(emoji: "📅", name: "calendar", keywords: ["date"]),
            .init(emoji: "🕐", name: "clock", keywords: ["time"]),
            .init(emoji: "⏰", name: "alarm", keywords: ["clock"]),
            .init(emoji: "💰", name: "money_bag", keywords: ["cash"]),
            .init(emoji: "💸", name: "money_flying", keywords: []),
            .init(emoji: "💳", name: "credit_card", keywords: []),
            .init(emoji: "📊", name: "bar_chart", keywords: ["graph"]),
            .init(emoji: "📈", name: "chart_up", keywords: ["growth"]),
            .init(emoji: "📉", name: "chart_down", keywords: []),
            .init(emoji: "📝", name: "memo", keywords: ["note"]),
            .init(emoji: "✏️", name: "pencil", keywords: ["edit"]),
            .init(emoji: "🖥", name: "computer", keywords: ["mac"]),
            .init(emoji: "💻", name: "laptop", keywords: []),
            .init(emoji: "⌨️", name: "keyboard", keywords: []),
            .init(emoji: "📱", name: "phone_mobile", keywords: ["mobile"]),
            .init(emoji: "🔋", name: "battery", keywords: []),
            .init(emoji: "🔌", name: "plug", keywords: []),
            .init(emoji: "💾", name: "save", keywords: ["floppy"]),
            .init(emoji: "🔒", name: "lock", keywords: ["secure"]),
            .init(emoji: "🔓", name: "unlock", keywords: []),
            .init(emoji: "🔑", name: "key", keywords: []),
            .init(emoji: "🛠", name: "tools", keywords: ["fix"]),
            .init(emoji: "🔨", name: "hammer", keywords: []),
            .init(emoji: "⚙️", name: "gear", keywords: ["settings"]),
            .init(emoji: "📦", name: "package", keywords: ["box"]),
            .init(emoji: "🚚", name: "truck", keywords: ["delivery"]),
        ]),
        Category(id: "animals", title: "Nature", symbol: "leaf", entries: [
            .init(emoji: "🐶", name: "dog", keywords: ["puppy"]),
            .init(emoji: "🐱", name: "cat", keywords: ["kitty"]),
            .init(emoji: "🐭", name: "mouse", keywords: []),
            .init(emoji: "🐹", name: "hamster", keywords: []),
            .init(emoji: "🐰", name: "rabbit", keywords: ["bunny"]),
            .init(emoji: "🦊", name: "fox", keywords: []),
            .init(emoji: "🐻", name: "bear", keywords: []),
            .init(emoji: "🐼", name: "panda", keywords: []),
            .init(emoji: "🐨", name: "koala", keywords: []),
            .init(emoji: "🐯", name: "tiger", keywords: []),
            .init(emoji: "🦁", name: "lion", keywords: []),
            .init(emoji: "🐮", name: "cow", keywords: []),
            .init(emoji: "🐷", name: "pig", keywords: []),
            .init(emoji: "🐸", name: "frog", keywords: []),
            .init(emoji: "🐵", name: "monkey", keywords: []),
            .init(emoji: "🐔", name: "chicken", keywords: []),
            .init(emoji: "🐧", name: "penguin", keywords: []),
            .init(emoji: "🐦", name: "bird", keywords: []),
            .init(emoji: "🦆", name: "duck", keywords: []),
            .init(emoji: "🦄", name: "unicorn", keywords: []),
            .init(emoji: "🐝", name: "bee", keywords: []),
            .init(emoji: "🐛", name: "bug", keywords: []),
            .init(emoji: "🐞", name: "ladybug", keywords: []),
            .init(emoji: "🦋", name: "butterfly", keywords: []),
            .init(emoji: "🐢", name: "turtle", keywords: []),
            .init(emoji: "🐍", name: "snake", keywords: []),
            .init(emoji: "🐙", name: "octopus", keywords: []),
            .init(emoji: "🐠", name: "fish", keywords: []),
            .init(emoji: "🌍", name: "earth", keywords: ["world"]),
            .init(emoji: "🌙", name: "moon", keywords: []),
            .init(emoji: "☀️", name: "sunny", keywords: ["sun"]),
            .init(emoji: "🌤", name: "partly_sunny", keywords: []),
            .init(emoji: "🌧", name: "rain", keywords: []),
            .init(emoji: "⛈", name: "thunderstorm", keywords: []),
            .init(emoji: "🌈", name: "rainbow", keywords: []),
            .init(emoji: "🌸", name: "blossom", keywords: ["flower"]),
            .init(emoji: "🌹", name: "rose", keywords: ["flower"]),
            .init(emoji: "🌻", name: "sunflower", keywords: []),
            .init(emoji: "🌳", name: "tree", keywords: []),
            .init(emoji: "🌴", name: "palm", keywords: []),
            .init(emoji: "🍀", name: "clover", keywords: ["luck"]),
            .init(emoji: "🍕", name: "pizza", keywords: []),
            .init(emoji: "🍔", name: "burger", keywords: []),
            .init(emoji: "🍟", name: "fries", keywords: []),
            .init(emoji: "🌮", name: "taco", keywords: []),
            .init(emoji: "🍜", name: "ramen", keywords: ["noodles"]),
            .init(emoji: "🍣", name: "sushi", keywords: []),
            .init(emoji: "🍩", name: "donut", keywords: []),
            .init(emoji: "🍪", name: "cookie", keywords: []),
            .init(emoji: "☕️", name: "coffee", keywords: []),
            .init(emoji: "🍺", name: "beer", keywords: []),
        ]),
    ]

    /// Flat search index over name + keywords. Returns matches across all
    /// categories, ordered by relevance (exact name > prefix > contains).
    static func search(_ query: String) -> [Entry] {
        let q = query.lowercased().trimmingCharacters(in: .whitespaces)
        guard !q.isEmpty else { return [] }
        let all = categories.flatMap(\.entries)
        let scored: [(Entry, Int)] = all.compactMap { e in
            if e.name == q { return (e, 1000) }
            if e.name.hasPrefix(q) { return (e, 500) }
            if e.name.contains(q) { return (e, 200) }
            if e.keywords.contains(where: { $0.hasPrefix(q) }) { return (e, 100) }
            if e.keywords.contains(where: { $0.contains(q) }) { return (e, 50) }
            return nil
        }
        return scored.sorted { $0.1 > $1.1 }.map(\.0)
    }
}
